
ALTER TABLE public.model_statistics
  ADD COLUMN IF NOT EXISTS role_used TEXT,
  ADD COLUMN IF NOT EXISTS task_id UUID,
  ADD COLUMN IF NOT EXISTS hallucination_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS arbiter_score NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS arbiter_eval_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS critique_summary TEXT,
  ADD COLUMN IF NOT EXISTS contest_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS contest_total_score NUMERIC NOT NULL DEFAULT 0;
